$defs:
  level:
    description: Level is the level of internal telemetry (metrics, logs, traces about the component itself) that every component should generate.
    type: integer
    x-customType: int32
