dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.71.0-dev
  otelcol_version: 0.71.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.71.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.71.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.71.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.71.0
extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.71.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.71.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.71.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.71.0
connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.71.0

