version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "16686:16686"
      - "14268"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:2.11.12
    ports:
      - "9411:9411"

  # Collector
  oc-collector:
    image: collector:latest
    command: ["--config=/etc/oc-collector-config.yaml", "--http-pprof-port=1777"]
    volumes:
      - ./oc-collector-config.yaml:/etc/oc-collector-config.yaml
    ports:
      - "55678"
      - "55680:55679"
      - "1777:1777"
      - "8888:8888" # Prometheus metrics
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  # Agent
  oc-agent:
    image: collector:latest
    command: ["--config=/etc/oc-agent-config.yaml", "--http-pprof-port=1888"]
    volumes:
      - ./oc-agent-config.yaml:/etc/oc-agent-config.yaml
    ports:
      - "14268"
      - "55678"
      - "55679:55679"
    depends_on:
      - oc-collector

  # Synthetic load generator
  synthetic-load-generator:
    image: omnition/synthetic-load-generator:1.0.25
    environment:
      - JAEGER_COLLECTOR_URL=http://otelsvc-agent:14268
    depends_on:
      - oc-agent

