$defs:
  back_off_config:
    description: BackOffConfig defines configuration for retrying batches in case of export failure. The current supported strategy is exponential backoff.
    type: object
    properties:
      enabled:
        description: Enabled indicates whether to not retry sending batches in case of export failure.
        type: boolean
      initial_interval:
        description: InitialInterval the time to wait after the first failure before retrying.
        type: string
        x-customType: time.Duration
        format: duration
      max_elapsed_time:
        description: MaxElapsedTime is the maximum amount of time (including retries) spent trying to send a request/batch. Once this value is reached, the data is discarded. If set to 0, the retries are never stopped.
        type: string
        x-customType: time.Duration
        format: duration
      max_interval:
        description: MaxInterval is the upper bound on backoff interval. Once this value is reached the delay between consecutive retries will always be `MaxInterval`.
        type: string
        x-customType: time.Duration
        format: duration
      multiplier:
        description: Multiplier is the value multiplied by the backoff interval bounds
        type: number
        x-customType: float64
      randomization_factor:
        description: RandomizationFactor is a random factor used to calculate next backoffs Randomized interval = RetryInterval * (1 Â± RandomizationFactor)
        type: number
        x-customType: float64
