change_logs:
    api: CHANGELOG-API.md
    user: CHANGELOG.md
default_change_logs:
    - user
entries_dir: .chloggen
template_yaml: .chloggen/TEMPLATE.yaml
summary_template: .chloggen/summary.tmpl
components:
    - all
    - cmd/builder
    - cmd/mdatagen
    - connector/forward
    - connector/sample
    - consumer/consumererror/xconsumererror
    - consumer/xconsumer
    - docs/rfcs
    - exporter/debug
    - exporter/nop
    - exporter/otlp_grpc
    - exporter/otlp_http
    - extension/memory_limiter
    - extension/zpages
    - pdata/pprofile
    - pkg/client
    - pkg/component
    - pkg/component/componentstatus
    - pkg/component/componenttest
    - pkg/config/configauth
    - pkg/config/configcompression
    - pkg/config/configgrpc
    - pkg/config/confighttp
    - pkg/config/confighttp/xconfighttp
    - pkg/config/configmiddleware
    - pkg/config/confignet
    - pkg/config/configopaque
    - pkg/config/configoptional
    - pkg/config/configretry
    - pkg/config/configtelemetry
    - pkg/config/configtls
    - pkg/confmap
    - pkg/connector
    - pkg/connector/connectortest
    - pkg/consumer
    - pkg/consumer/consumererror
    - pkg/consumer/consumertest
    - pkg/exporter
    - pkg/exporter/exportertest
    - pkg/exporterhelper
    - pkg/extension
    - pkg/extension/extensiontest
    - pkg/extensionauth
    - pkg/extensionauth/extensionauthtest
    - pkg/extensioncapabilities
    - pkg/extensionmiddleware
    - pkg/extensionmiddleware/extensionmiddlewaretest
    - pkg/featuregate
    - pkg/filter
    - pkg/otelcol
    - pkg/otelcol/otelcoltest
    - pkg/pdata
    - pkg/pipeline
    - pkg/processor
    - pkg/processor/processortest
    - pkg/processorhelper
    - pkg/queuebatch
    - pkg/receiver
    - pkg/receiver/receivertest
    - pkg/receiverhelper
    - pkg/scraper
    - pkg/scraper/scrapertest
    - pkg/scraperhelper
    - pkg/service
    - pkg/service/hostcapabilities
    - pkg/service/telemetry/telemetrytest
    - pkg/xconfmap
    - pkg/xconnector
    - pkg/xexporter
    - pkg/xexporterhelper
    - pkg/xextension
    - pkg/xextension/storage
    - pkg/xpdata
    - pkg/xpipeline
    - pkg/xprocessor
    - pkg/xprocessorhelper
    - pkg/xreceiver
    - pkg/xscraper
    - pkg/xscraperhelper
    - processor/batch
    - processor/memory_limiter
    - processor/sample
    - provider/env
    - provider/file
    - provider/http
    - provider/https
    - provider/yaml
    - receiver/nop
    - receiver/otlp
    - receiver/sample
    - receiver/sample
    - scraper/sample
    - service/graph
