change_logs:
    api: CHANGELOG-API.md
    user: CHANGELOG.md
default_change_logs:
    - user
entries_dir: .chloggen
template_yaml: .chloggen/TEMPLATE.yaml
summary_template: .chloggen/summary.tmpl
components:
    - all
    - cmd/builder
    - cmd/mdatagen
    - connector/forward
    - connector/sample
    - consumer/xconsumer
    - docs/rfcs
    - exporter/debug
    - exporter/nop
    - exporter/otlp
    - exporter/otlphttp
    - extension/memory_limiter
    - extension/xextension
    - extension/xextension
    - extension/zpages
    - pdata/pprofile
    - pdata/xpdata
    - pkg/config/configauth
    - pkg/config/configcompression
    - pkg/config/configgrpc
    - pkg/config/confighttp
    - pkg/config/configmiddleware
    - pkg/config/confignet
    - pkg/config/configopaque
    - pkg/config/configoptional
    - pkg/config/configretry
    - pkg/config/configtelemetry
    - pkg/config/configtls
    - pkg/confmap
    - pkg/exporterhelper
    - pkg/otelcol
    - pkg/pdata
    - pkg/processorhelper
    - pkg/queuebatch
    - pkg/receiverhelper
    - pkg/scraper
    - pkg/scraperhelper
    - pkg/service
    - pkg/xconnector
    - pkg/xexporter
    - pkg/xexporterhelper
    - pkg/xprocessor
    - pkg/xreceiver
    - pkg/xscraper
    - processor/batch
    - processor/memory_limiter
    - processor/sample
    - provider/env
    - provider/file
    - provider/http
    - provider/https
    - provider/yaml
    - receiver/nop
    - receiver/otlp
    - receiver/sample
    - receiver/sample
    - scraper/sample
    - service/graph
