# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: service/pipelines

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add pipelines.Config to remove duplicate of the pipelines configuration

# One or more tracking issues or pull requests related to the change
issues: [7854]

