# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: service

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add `CollectorConfig` field to `service.Settings`

# One or more tracking issues or pull requests related to the change
issues: [6596]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  This field is intended to be used by the Collector to pass its effective configuration to the service.
