name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:

  Check-Compatibility:
    runs-on: macos-latest
    steps:

      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}

      - name: Generate-Compare-Check-apidiff
        run: |
          echo ::group::Generating apidiff states
          cd ${{ github.base_ref }}
          make install-tools
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          make apidiff-build
          echo ::endgroup::
          
          echo ::group::Comparing apidiff states
          cd ../${{ github.head_ref }}
          make apidiff-compare-GA input_dir="../${{ github.base_ref }}/internal/data/apidiff"
          echo ::endgroup::

          echo ::group::Checking incompatible apis
          make apidiff-check input_dir="../${{ github.base_ref }}/internal/data/apidiff"
          echo ::endgroup::
