name: "Inform incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_HEAD_REF"
      - run: echo "$GITHUB_BASE_REF"
      - run: echo "hello world"

      - run: echo "${{ github.base_ref }}"

      - run: echo "${{ github.base_ref.sha }}"
      
      - run: echo "$github.base_ref.sha"

      - run: echo "${{ github.event.pull_request.head.sha }}"

  Get-Multiple-Branches:
    runs-on: ubuntu-latest
    name: Checkout PR
      - steps: 
        - uses: actions/checkout@v2
        - with:
          - path: $GITHUB_BASE_REF"

    - name: Checkout Main
        - uses: actions/checkout@v2
        - with:
          - path: "$GITHUB_HEAD_REF"