name: Update OpenTelemetry Website Docs

on:
  release:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: make-pr
        env:
          API_TOKEN_GITHUB: ${{secrets.DOC_UPDATE_TOKEN}}
          # Destination repo should always be 'open-telemetry/opentelemetry.io'
          DESTINATION_REPO: open-telemetry/opentelemetry.io
          # Destination path should be the absolute path to your language's friendly name in the docs tree (i.e, 'content/en/docs/java')
          DESTINATION_PATH: content/en/docs/collector
          # Source path should be 'website_docs', all files and folders are copied from here to dest
          SOURCE_PATH: website_docs
        run: |
          TARGET_DIR=$(mktemp -d)
          export GITHUB_TOKEN=$API_TOKEN_GITHUB
          git config --global user.name austinlparker
          git config --global user.email austin@lightstep.com
          git clone "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_REPO.git" "$TARGET_DIR"
          rsync -av --delete "$SOURCE_PATH/" "$TARGET_DIR/$DESTINATION_PATH/"
          cd "$TARGET_DIR"
          git checkout -b docs-$GITHUB_REPOSITORY-$GITHUB_SHA
          git add .
          git commit -m "Docs update from $GITHUB_REPOSITORY"
          git push -u origin HEAD:docs-$GITHUB_REPOSITORY-$GITHUB_SHA
          gh pr create -t "Docs Update from $GITHUB_REPOSITORY" -b "This is an automated pull request." -B main -H docs-$GITHUB_REPOSITORY-$GITHUB_SHA
          echo "done"
          
