description: Config defines configuration for OTLP exporter.
type: object
properties:
  retry_on_failure:
    $ref: go.opentelemetry.io/collector/config/configretry.back_off_config
  sending_queue:
    x-optional: true
    $ref: go.opentelemetry.io/collector/exporter/exporterhelper.queue_batch_config
allOf:
  - $ref: go.opentelemetry.io/collector/exporter/exporterhelper.timeout_config
  - $ref: go.opentelemetry.io/collector/config/configgrpc.client_config
