$schema: https://json-schema.org/draft/2020-12/schema
$id: go.opentelemetry.io/collector/exporter/otlpexporter
title: otlpexporter component
description: Config defines configuration for OTLP exporter.
type: object
properties:
  retry_on_failure:
    $ref: go.opentelemetry.io/collector/config/configretry#/$defs/BackOffConfig
  sending_queue:
    x-optional: true
    $ref: go.opentelemetry.io/collector/exporter/exporterhelper#/$defs/QueueBatchConfig
allOf:
  - $ref: go.opentelemetry.io/collector/exporter/exporterhelper#/$defs/TimeoutConfig
  - $ref: go.opentelemetry.io/collector/config/configgrpc#/$defs/ClientConfig
